"""
BuilderAgent — The real code-building agent that:
  1. Creates a sandboxed workspace (git branch)
  2. Uses Gemini to plan and write code changes
  3. Runs tests inside the sandbox
  4. Commits changes and creates a PR for human review

This is the core "agentic loop" that turns a natural-language task
into actual, reviewable code modifications.
"""

import os
import json
import asyncio
import logging
from datetime import datetime, timezone

from backend.services.sandbox_manager import SandboxManager, SandboxSession
from backend.services.agent_registry import AGENT_REGISTRY, AgentDefinition
from backend.services.tool_registry import ToolRegistry
from backend.models.agent import AgentType

logger = logging.getLogger(__name__)


class BuilderAgent:
    """
    End-to-end builder that takes a task description and produces
    a branch of code changes inside an isolated sandbox.
    """

    def __init__(self):
        self.api_key = os.environ.get("GEMINI_API_KEY")
        self.client = None
        if self.api_key:
            from google import genai
            self.client = genai.Client(api_key=self.api_key)

    async def build(
        self,
        project_root: str,
        task_description: str,
        agent_type: AgentType = AgentType.BACKEND_ENGINEER,
        max_iterations: int = 15,
    ) -> dict:
        """
        Full build cycle:
          1. Create sandbox
          2. Run agentic loop (plan → code → test → iterate)
          3. Commit + create PR
          4. Return results
        """
        # ── Step 1: Create Sandbox ──────────────────────────────────
        sandbox = SandboxManager.create_sandbox(project_root, task_description)
        logger.info(f"[Builder] Sandbox created: {sandbox.session_id} on branch {sandbox.branch_name}")

        build_log: list[dict] = []

        def log_step(phase: str, detail: str, data: dict = None):
            entry = {
                "phase": phase,
                "detail": detail,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "data": data or {},
            }
            build_log.append(entry)
            logger.info(f"[Builder][{phase}] {detail}")

        log_step("SANDBOX", f"Created sandbox {sandbox.session_id}", {"branch": sandbox.branch_name})

        # ── Step 2: Build sandbox-scoped tools ──────────────────────
        sandbox_tools = self._build_sandbox_tools(sandbox)

        # ── Step 3: Run the agentic coding loop ─────────────────────
        if not self.client:
            # Mock mode: simulate code changes
            result = await self._mock_build(sandbox, task_description, build_log, log_step)
        else:
            result = await self._real_build(
                sandbox, task_description, agent_type,
                sandbox_tools, max_iterations, build_log, log_step
            )

        # ── Step 4: Commit and Create PR ────────────────────────────
        if sandbox.files_changed:
            commit_msg = f"feat: {task_description[:60]}\n\nGenerated by Kobits Builder Agent ({agent_type.value})"
            commit_result = SandboxManager.commit_changes(sandbox.session_id, commit_msg)
            log_step("COMMIT", f"Committed {len(sandbox.files_changed)} files", commit_result)

            pr_result = SandboxManager.create_pr(
                sandbox.session_id,
                title=f"[Kobits AI] {task_description[:60]}",
                body=self._generate_pr_body(task_description, sandbox, build_log),
            )
            log_step("PR", f"Pull request created: {pr_result.get('pr_url', 'N/A')}", pr_result)
        else:
            pr_result = {"message": "No files were changed."}
            log_step("PR", "Skipped — no files changed")

        return {
            "session_id": sandbox.session_id,
            "branch": sandbox.branch_name,
            "files_changed": sandbox.files_changed,
            "build_log": build_log,
            "pr": pr_result,
            "status": "SUCCESS" if sandbox.files_changed else "NO_CHANGES",
        }

    def _build_sandbox_tools(self, sandbox: SandboxSession) -> dict:
        """
        Build tool handlers that are scoped to THIS sandbox session.
        Instead of writing to the real project, all I/O goes into the sandbox dir.
        """
        sid = sandbox.session_id

        async def sandbox_read_file(path: str) -> dict:
            return SandboxManager.read_file(sid, path)

        async def sandbox_write_file(path: str, content: str) -> dict:
            return SandboxManager.write_file(sid, path, content)

        async def sandbox_run_command(command: str) -> dict:
            return SandboxManager.run_command(sid, command)

        async def sandbox_list_files(path: str = ".") -> dict:
            return SandboxManager.read_file(sid, path)

        async def sandbox_search_files(query: str) -> dict:
            """Grep-like search inside the sandbox."""
            result = SandboxManager.run_command(
                sid, f'findstr /S /I /N /C:"{query}" *.py *.js *.html *.css *.md'
            )
            return result

        async def sandbox_run_tests(test_command: str = "python -m pytest -x -q") -> dict:
            return SandboxManager.run_command(sid, test_command, timeout=120)

        async def sandbox_git_diff() -> dict:
            return SandboxManager.get_diff(sid)

        return {
            "sandbox_read_file": sandbox_read_file,
            "sandbox_write_file": sandbox_write_file,
            "sandbox_run_command": sandbox_run_command,
            "sandbox_list_files": sandbox_list_files,
            "sandbox_search_files": sandbox_search_files,
            "sandbox_run_tests": sandbox_run_tests,
            "sandbox_git_diff": sandbox_git_diff,
        }

    async def _mock_build(self, sandbox, task_description, build_log, log_step) -> dict:
        """Simulate a build when no API key is available."""
        log_step("PLAN", "Mock mode — simulating code generation")

        # Simulate reading the project structure
        project_listing = SandboxManager.read_file(sandbox.session_id, ".")
        log_step("EXPLORE", "Scanned project structure", project_listing)

        # Simulate creating a new file
        mock_code = f'''"""
Auto-generated by Kobits Builder Agent
Task: {task_description}
Generated at: {datetime.now(timezone.utc).isoformat()}
"""

# TODO: This is a placeholder generated by the mock builder.
# In production, Gemini would generate real implementation code here.

def main():
    """Entry point for the generated feature."""
    print("Feature: {task_description[:40]}")
    return {{"status": "implemented"}}

if __name__ == "__main__":
    main()
'''
        SandboxManager.write_file(sandbox.session_id, "generated/feature.py", mock_code)
        log_step("CODE", "Generated generated/feature.py", {"file": "generated/feature.py"})

        # Simulate creating a test
        mock_test = f'''"""Auto-generated test for the builder output."""
import sys
sys.path.insert(0, ".")

def test_feature_exists():
    """Verify the generated module is importable."""
    from generated import feature
    assert hasattr(feature, "main")

def test_feature_runs():
    """Verify the entry point returns expected structure."""
    from generated import feature
    result = feature.main()
    assert result["status"] == "implemented"
'''
        SandboxManager.write_file(sandbox.session_id, "generated/test_feature.py", mock_test)
        # Create __init__.py
        SandboxManager.write_file(sandbox.session_id, "generated/__init__.py", "")
        log_step("TEST", "Generated test_feature.py")

        # Simulate running tests
        test_result = SandboxManager.run_command(
            sandbox.session_id, "python -m pytest generated/test_feature.py -v", timeout=30
        )
        log_step("VERIFY", "Ran tests", test_result)

        return {"status": "SUCCESS", "summary": "Mock build completed."}

    async def _real_build(
        self, sandbox, task_description, agent_type,
        sandbox_tools, max_iterations, build_log, log_step
    ) -> dict:
        """Run the real Gemini-powered agentic coding loop."""
        from google.genai import types

        agent_def = AGENT_REGISTRY[agent_type]

        # Build tool declarations for Gemini
        tool_declarations = []
        tool_map = {}

        tool_specs = [
            ("sandbox_read_file", "Read a file or list a directory from the project sandbox.",
             {"type": "OBJECT", "properties": {"path": {"type": "STRING"}}, "required": ["path"]}),
            ("sandbox_write_file", "Write or create a file in the project sandbox. Provide the FULL content.",
             {"type": "OBJECT", "properties": {
                 "path": {"type": "STRING", "description": "Relative file path"},
                 "content": {"type": "STRING", "description": "Complete file content"}
             }, "required": ["path", "content"]}),
            ("sandbox_run_command", "Run a shell command inside the sandbox directory.",
             {"type": "OBJECT", "properties": {"command": {"type": "STRING"}}, "required": ["command"]}),
            ("sandbox_list_files", "List files in a directory.",
             {"type": "OBJECT", "properties": {"path": {"type": "STRING"}}, "required": ["path"]}),
            ("sandbox_search_files", "Search for a pattern across all source files.",
             {"type": "OBJECT", "properties": {"query": {"type": "STRING"}}, "required": ["query"]}),
            ("sandbox_run_tests", "Run the test suite inside the sandbox.",
             {"type": "OBJECT", "properties": {"test_command": {"type": "STRING"}}, "required": ["test_command"]}),
            ("sandbox_git_diff", "See all changes made so far as a git diff.",
             {"type": "OBJECT", "properties": {}, "required": []}),
        ]

        for name, desc, schema in tool_specs:
            tool_declarations.append(types.FunctionDeclaration(
                name=name, description=desc, parameters=schema
            ))
            tool_map[name] = sandbox_tools[name]

        system_prompt = f"""You are a Kobits Builder Agent ({agent_def.name} — {agent_type.value}).
Your job is to ACTUALLY IMPLEMENT code changes inside an isolated sandbox workspace.

RULES:
1. First, explore the project structure using sandbox_list_files and sandbox_read_file.
2. Understand the existing code patterns and conventions.
3. Plan your changes, then implement them using sandbox_write_file.
4. After writing code, run tests using sandbox_run_tests to verify.
5. If tests fail, read the errors, fix the code, and re-run.
6. When done, call sandbox_git_diff to review your changes.
7. Write COMPLETE file contents — never partial snippets.
8. Follow existing code style and conventions.
9. Create or update tests for any new functionality.

You are working inside an isolated sandbox. Your changes will be packaged as a PR for human review.

{agent_def.system_prompt}
"""

        config = types.GenerateContentConfig(
            system_instruction=system_prompt,
            temperature=0.1,
            tools=[types.Tool(function_declarations=tool_declarations)],
        )

        chat = self.client.aio.chats.create(model="gemini-2.5-pro", config=config)
        current_message = f"Task: {task_description}\n\nPlease explore the codebase and implement this feature."

        log_step("PLAN", f"Starting agentic loop with {agent_type.value}")

        for iteration in range(max_iterations):
            try:
                response = await chat.send_message(current_message)
            except Exception as e:
                log_step("ERROR", f"LLM call failed: {e}")
                break

            if response.function_calls:
                func_responses = []
                for fc in response.function_calls:
                    handler = tool_map.get(fc.name)
                    if handler:
                        try:
                            tool_result = await handler(**(fc.args or {}))
                        except Exception as e:
                            tool_result = {"error": str(e)}
                        log_step("TOOL", f"{fc.name}({json.dumps(fc.args)[:80]}…)", tool_result)
                    else:
                        tool_result = {"error": f"Unknown tool: {fc.name}"}

                    func_responses.append(types.Part.from_function_response(
                        name=fc.name, response=tool_result
                    ))

                current_message = func_responses
            else:
                # Final text response — agent is done
                log_step("DONE", f"Agent completed after {iteration + 1} iterations")
                if response.text:
                    log_step("SUMMARY", response.text[:500])
                break

        return {"status": "SUCCESS", "iterations": iteration + 1}

    def _generate_pr_body(self, task_description: str, sandbox: SandboxSession, build_log: list) -> str:
        """Generate a nice markdown PR description."""
        phases = [e["phase"] for e in build_log]
        files = "\n".join(f"- `{f}`" for f in sandbox.files_changed) if sandbox.files_changed else "- No files changed"

        return f"""## 🤖 Kobits AI Builder — Auto-Generated PR

### Task
> {task_description}

### Files Changed
{files}

### Build Log
| Phase | Detail |
|-------|--------|
{chr(10).join(f'| {e["phase"]} | {e["detail"][:80]} |' for e in build_log)}

### Branch
`{sandbox.branch_name}`

---
*Generated by Kobits Builder Agent*
"""


# ── Global instance ──
builder_agent = BuilderAgent()
