from abc import ABC, abstractmethod
import asyncio
import json
from backend.models.agent import AgentRun, AgentType
from backend.services.agent_registry import AGENT_REGISTRY

class AbstractLLMProvider(ABC):
    @abstractmethod
    async def generate_json(self, system_prompt: str, user_prompt: str, schema: dict, model_tier: str = "reasoning") -> dict:
        pass


class ModelRouter:
    """Routes requests to the appropriate model tier (fast, coding, reasoning)."""
    @staticmethod
    def get_model_for_tier(tier: str) -> str:
        if tier == "fast":
            return "kobits-fast-1.5"
        elif tier == "coding":
            return "kobits-code-2.0"
        else: # reasoning
            return "kobits-pro-2.0"
            
    @staticmethod
    def get_cost_per_1k_tokens(model: str) -> float:
        costs = {
            "kobits-fast-1.5": 0.0001,
            "kobits-code-2.0": 0.002,
            "kobits-pro-2.0": 0.01
        }
        return costs.get(model, 0.001)


class MockLLMProvider(AbstractLLMProvider):
    async def generate_json(self, system_prompt: str, user_prompt: str, schema: dict, model_tier: str = "reasoning") -> dict:
        # Simulate network delay for realism
        await asyncio.sleep(2)
        
        # We try to mock a sensible response based on the agent's expected output schema
        
        # If it's the standard AgentOutputSchema:
        if "requires_approval" in schema.get("properties", {}):
            return {
                "status": "SUCCESS",
                "summary": f"Completed tasks using {model_tier} model.",
                "findings": ["Analyzed project context.", "No major issues found."],
                "changes": ["Updated relevant modules."],
                "recommendations": ["Review deployment pipelines."],
                "risks": ["Potential downtime during migration."],
                "next_actions": ["Proceed to QA."],
                "artifacts": {"summary.md": "# Work Complete\nAll tasks finished successfully."},
                "requires_approval": False
            }
            
        # Fallback for Orchestrator Plan
        return {
            "summary": "This is a mocked execution plan generated by the LLM.",
            "phases": [
                {"name": "Requirements", "description": "Gather requirements", "status": "pending"},
                {"name": "Implementation", "description": "Write code", "status": "pending"},
                {"name": "Review", "description": "Review code", "status": "pending"}
            ],
            "estimated_days": 3,
            "recommended_agents": ["PRODUCT_MANAGER", "BACKEND_ENGINEER"]
        }


# Global instances
llm_provider = MockLLMProvider()

async def execute_agent_run(agent_run: AgentRun, agent_type: AgentType, input_data: dict) -> dict:
    """Executes an agent run using the standard agent contract."""
    
    agent_def = AGENT_REGISTRY[agent_type]
    model_tier = agent_def.default_model
    model_name = ModelRouter.get_model_for_tier(model_tier)
    
    agent_run.model = model_name
    agent_run.status = "RUNNING"
    
    # Define standard output schema
    schema = {
        "type": "object",
        "properties": {
            "status": {"type": "string"},
            "summary": {"type": "string"},
            "findings": {"type": "array", "items": {"type": "string"}},
            "changes": {"type": "array", "items": {"type": "string"}},
            "recommendations": {"type": "array", "items": {"type": "string"}},
            "risks": {"type": "array", "items": {"type": "string"}},
            "next_actions": {"type": "array", "items": {"type": "string"}},
            "artifacts": {"type": "object"},
            "requires_approval": {"type": "boolean"}
        }
    }
    
    user_prompt = json.dumps(input_data, indent=2)
    
    # Execute LLM
    result = await llm_provider.generate_json(
        system_prompt=agent_def.system_prompt,
        user_prompt=user_prompt,
        schema=schema,
        model_tier=model_tier
    )
    
    # Mock token usage & cost
    input_tokens = len(user_prompt) // 4
    output_tokens = len(json.dumps(result)) // 4
    agent_run.tokens_input += input_tokens
    agent_run.tokens_output += output_tokens
    
    cost_per_1k = ModelRouter.get_cost_per_1k_tokens(model_name)
    agent_run.estimated_cost += ((input_tokens + output_tokens) / 1000.0) * cost_per_1k
    
    agent_run.output_text = json.dumps(result)
    
    return result
